sudo: required

language: rust
rust:
    - nightly
cache:
    - cargo: true
    # TODO: dedup this with the MODULE_DIR in env
    - directories:
        - static-filesystem/target/
        - hello-world/target/
        - example-sysctl/target/

branches:
    only:
        - master

matrix:
    include:
        - env: MODULE_DIR=hello-world MODULE=helloworld
        - env: MODULE_DIR=static-filesystem MODULE=staticfilesystem
        - env: MODULE_DIR=example-sysctl MODULE=examplesysctl

install:
    - sudo apt-get install -y "linux-headers-$(uname -r)"
    - type -p cargo-install-update || cargo install --force cargo-update
    - |
      if type -p cargo-xbuild; then
          cargo install-update -i cargo-xbuild
      else
          cargo install --force cargo-xbuild
      fi
    - rustup component add rust-src

script:
    - cd $MODULE_DIR
    - RUST_TARGET_PATH="$(pwd)/.." cargo xbuild --target x86_64-linux-kernel-module
    - make
    - sudo dmesg -C
    - sudo insmod "${MODULE}.ko"
    - sudo rmmod "$MODULE"

after_failure:
    - dmesg

notifications:
    email: false
