[package]
name = "linux-kernel-module"
version = "0.1.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]

[dependencies]
bitflags = "1"

[build-dependencies]
bindgen = "*"
nix = "0.10"
shlex = "0.1"
