[package]
name = "static-filesystem"
version = "0.1.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
linux-kernel-module = { path = ".." }

[profile.dev]
# TODO: can be removed once we have a custom target.json
panic = "abort"
